### ISSUE TITLE
0.3.0 build

### ISSUE THREAD

**Issue by gypapp** [burtcorp/jmespath-java-contrib#4]
Hello @iconara, I tagged the repository with the same version (`0.3.0`) as the main package but don't exactly know the build process.

Would you mind making a build and publish the package that I can refer to?

**Comment by iconara** [comment]
Will do

**Comment by iconara** [comment]
Now released. I've also changed the tags to match how jmespath-java is tagged (e.g. `jmespath-contrib-0.3.0` instead of just `0.3.0`). Maven automatically tags when you release so next time you don't need to tag yourself. I think that I'm the only one that is allowed to release to the `io.burt` namespace on Maven, so I will have to do the releases. Just ping me like you did this time and I'll do it as soon as I can (you can assign me to the issue too).

**Comment by gypapp** [comment]
👍 many thanks.

When do you think I should expect to appear in [maven central](https://search.maven.org/search?q=jmespath-contrib)?

**Comment by gypapp** [comment]
Now it is there.
